# Generated by Django 4.0.5 on 2022-07-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fav',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
